### ISSUE TITLE
readme additional instruction

### ISSUE THREAD

**Issue by kaosbeat** [tacoe/op1go#1]
Hi downloaded latest raspbian lite as per instructions.

USB connection was fine, but to enable the "apt-get upgrade" and other internet needing commands I had to enable MacOSX internet sharing (to the "RNDIS Ethernet Gadget")

further down, I had to  add the share in 
`/etc/netatalk/afp.conf`

like:
```
[op1go]
path = /op1go
```

other than that...

works great!

**Comment by tacoe** [comment]
I've added this to the readme. Thank you very much!
